services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  web:
    image: odoo:17
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons

volumes:
  odoo-web-data:
  odoo-db-data:

